name: basics

on:
  workflow_call:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  basics:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        steps:
          - name: check
            run: ci-check
          - name: fmt
            run: ci-fmt
          - name: clippy
            run: ci-clippy
          - name: sort
            run: ci-sort
    steps:
      - uses: actions/checkout@v3
      - uses: Swatinem/rust-cache@v2
      - uses: cachix/install-nix-action@v19
        with:
          github_access_token: ${{ secrets.GITHUB_TOKEN }}
      - name: ${{ matrix.steps.name }}
        run: |
          nix develop --command \
          pre-commit run --all-files \
          ${{ matrix.steps.run }}
